import { ArrowRight, Bell, BellRing, CalendarDays, Check, Clock3, Compass, Settings2, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import type { CampusEvent, CampusNotification, NotificationPreferences, UserRole } from "../types";
import { EmptyState, EventCard, EventRow, SectionHeading } from "../components/UI";

export function SavedPage({ events, savedIds, registeredIds, onOpen, onSave, onDiscover }: { events: CampusEvent[]; savedIds: string[]; registeredIds: string[]; onOpen: (id: string) => void; onSave: (id: string) => void; onDiscover: () => void }) {
  const saved = events.filter((event) => savedIds.includes(event.id));
  return <div className="page-content"><header className="page-title-row"><div><p className="welcome-date">Keep the good ones close</p><h1>Your saved events.</h1><p className="welcome-subtitle">A short list for your future self.</p></div></header>{saved.length ? <div className="event-card-grid">{saved.map((event) => <EventCard key={event.id} event={event} saved registered={registeredIds.includes(event.id)} onOpen={() => onOpen(event.id)} onSave={() => onSave(event.id)} />)}</div> : <EmptyState title="Your list is still open" detail="Save an event that catches your eye, and it’ll be waiting right here." action={<button className="button button-primary" onClick={onDiscover}><Compass size={16} />Explore events</button>} />}</div>;
}

export function CalendarPage({ events, registeredIds, savedIds, onOpen }: { events: CampusEvent[]; registeredIds: string[]; savedIds: string[]; onOpen: (id: string) => void }) {
  const plans = events.filter((event) => registeredIds.includes(event.id) || savedIds.includes(event.id)).sort((a, b) => a.date.localeCompare(b.date));
  return <div className="page-content"><header className="page-title-row"><div><p className="welcome-date">Make room for something new</p><h1>Your calendar.</h1><p className="welcome-subtitle">The events and deadlines you don’t want to miss.</p></div><span className="calendar-count"><CalendarDays size={17} />{plans.length} plans</span></header><div className="calendar-layout"><section className="calendar-month-card"><div className="calendar-month-heading"><span>{new Intl.DateTimeFormat("en", { month: "long", year: "numeric" }).format(new Date())}</span><span>Campus plans</span></div><div className="calendar-weekdays">{["M", "T", "W", "T", "F", "S", "S"].map((day, index) => <span key={`${day}-${index}`}>{day}</span>)}</div><div className="calendar-day-grid">{Array.from({ length: 35 }, (_, i) => { const date = new Date(); const firstDay = (new Date(date.getFullYear(), date.getMonth(), 1).getDay() + 6) % 7; const number = i - firstDay + 1; const inMonth = number > 0 && number <= new Date(date.getFullYear(), date.getMonth() + 1, 0).getDate(); const hasEvent = inMonth && plans.some((event) => new Date(event.date).getDate() === number); return <span key={i} className={`${inMonth ? "" : "outside-month"} ${inMonth && number === date.getDate() ? "today" : ""} ${hasEvent ? "has-event" : ""}`}>{inMonth ? number : ""}{hasEvent && <i />}</span>; })}</div><div className="calendar-key"><span><i className="calendar-key-blue" />Registered</span><span><i className="calendar-key-yellow" />Saved</span></div></section><section className="calendar-upcoming"><SectionHeading title="Coming up" detail="Your next campus moments." />{plans.length ? plans.map((event) => <div className="calendar-event-row" key={event.id}><span className={`calendar-event-marker ${registeredIds.includes(event.id) ? "marker-blue" : "marker-yellow"}`} /><EventRow event={event} onOpen={() => onOpen(event.id)} /></div>) : <EmptyState title="A blank page, for now" detail="Register or save an event and it will appear in your calendar." />}</section></div></div>;
}

export function NotificationsPage({ notifications, onRead, onReadAll, onOpen }: { notifications: CampusNotification[]; onRead: (id: string) => void; onReadAll: () => void; onOpen: (id: string) => void }) {
  return <div className="page-content"><header className="page-title-row"><div><p className="welcome-date">Only the things worth your attention</p><h1>Your notifications.</h1><p className="welcome-subtitle">Helpful reminders, never a campus-wide pile-on.</p></div>{notifications.some((note) => !note.read) && <button className="button button-subtle" onClick={onReadAll}><Check size={15} />Mark all read</button>}</header><div className="notification-list">{notifications.length ? notifications.map((note) => <article key={note.id} className={`notification-row ${note.read ? "" : "unread"}`}><span className={`notification-type-icon ${note.priority}`}><BellRing size={17} /></span><button className="notification-copy" onClick={() => { onRead(note.id); if (note.eventId) onOpen(note.eventId); }}><span className="notification-heading">{note.title}{!note.read && <i />}</span><span>{note.body}</span><small><Clock3 size={13} />{note.time}</small></button><span className={`notification-priority ${note.priority}`}>{note.priority}</span></article>) : <EmptyState title="All caught up" detail="When something useful happens, you’ll see it here." />}</div></div>;
}

export function SettingsPage({ role, interests, notificationPreferences, onInterestsChange, onPreferenceChange, onReset }: { role: UserRole; interests: string[]; notificationPreferences: NotificationPreferences; onInterestsChange: (interests: string[]) => void; onPreferenceChange: (key: keyof NotificationPreferences, value: boolean) => void; onReset: () => void }) {
  return <div className="page-content"><header className="page-title-row"><div><p className="welcome-date">Make this space yours</p><h1>Your settings.</h1><p className="welcome-subtitle">Keep your feed close to what you care about.</p></div></header><div className="settings-layout"><section className="settings-card"><SectionHeading title="Your campus profile" detail="A few details help us find a better signal." /><div className="profile-summary"><span className="profile-avatar-large">MC</span><span><strong>Maya Chen</strong><small>Computer Science · 2nd year</small></span><span className="profile-role-tag"><UserRound size={13} />{role}</span></div><label className="form-label">Your interests<div className="form-choice-grid">{["AI & ML", "Design", "Career", "Robotics", "Business", "Research", "Photography", "Technology"].map((interest) => <button type="button" aria-pressed={interests.includes(interest)} className={`filter-chip ${interests.includes(interest) ? "selected" : ""}`} onClick={() => onInterestsChange(interests.includes(interest) ? interests.filter((item) => item !== interest) : [...interests, interest])} key={interest}>{interest}</button>)}</div></label></section><section className="settings-card"><SectionHeading title="A calmer inbox" detail="We’ll only get in touch when it helps." /><div className="settings-option"><span className="settings-option-icon"><Bell size={17} /></span><span><strong>Event reminders</strong><small>A nudge before you’re due to arrive.</small></span><input type="checkbox" checked={notificationPreferences.reminders} onChange={(event) => onPreferenceChange("reminders", event.target.checked)} aria-label="Event reminders enabled" /></div><div className="settings-option"><span className="settings-option-icon"><Sparkles size={17} /></span><span><strong>Recommendations</strong><small>New things that fit what you like.</small></span><input type="checkbox" checked={notificationPreferences.recommendations} onChange={(event) => onPreferenceChange("recommendations", event.target.checked)} aria-label="Recommendations enabled" /></div><div className="settings-option"><span className="settings-option-icon"><Settings2 size={17} /></span><span><strong>Organizer announcements</strong><small>Updates for events you’re going to.</small></span><input type="checkbox" checked={notificationPreferences.announcements} onChange={(event) => onPreferenceChange("announcements", event.target.checked)} aria-label="Organizer announcements enabled" /></div></section><section className="settings-card role-info-card"><ShieldCheck size={19} /><div><strong>Demo workspace</strong><p>You’re exploring Campus Signal as <b>{role}</b>. Your changes stay in this browser.</p><button className="text-link" onClick={onReset}>Reset demo workspace <ArrowRight size={14} /></button></div></section></div></div>;
}
